#!/bin/bash

# OS segment 
OS_ICON=""

# Distro segment
DISTRO_ICON=""
DISTRO_NORMAL_ICON_COLOR="#2AA198"
DISTRO_WARN_ICON_COLOR="#B58900"

# Clock segment
CLOCK_ICON_01=""
CLOCK_ICON_02=""
CLOCK_ICON_03=""
CLOCK_ICON_04=""
CLOCK_ICON_05=""
CLOCK_ICON_06=""
CLOCK_ICON_07=""
CLOCK_ICON_08=""
CLOCK_ICON_09=""
CLOCK_ICON_10=""
CLOCK_ICON_11=""
CLOCK_ICON_12=""
CLOCK_ICON_COLOR="#2AA198"
CLOCK_FORMAT="%H:%M"

# Date segment
DATE_ICON=""
DATE_ICON_COLOR="#2AA198"
DATE_FORMAT="%d-%m-%Y"

# Mail segment
MAIL_NORMAL_ICON=""
MAIL_WARN_ICON=""
MAIL_NORMAL_ICON_COLOR="#2AA198"
MAIL_WARN_ICON_COLOR="#B58900"

# Message segment
MESSAGE_NORMAL_ICON=""
MESSAGE_WARN_ICON=""
MESSAGE_NORMAL_ICON_COLOR="#2AA198"
MESSAGE_WARN_ICON_COLOR="#B58900"

# Mail segment
MAIL_NORMAL_ICON=""
MAIL_WARN_ICON=""
MAIL_NORMAL_ICON_COLOR="#2AA198"
MAIL_WARN_ICON_COLOR="#B58900"

# Battery segment
BATTERY_ICON_CRITICAL=""
BATTERY_ICON_VERY_LOW=""
BATTERY_ICON_LOW=""
BATTERY_ICON_MEDIUM=""
BATTERY_ICON_HIGH=""
BATTERY_ICON_VERY_HIGH=""
BATTERY_ICON_MAX=""
BATTERY_ICON_FULL=""
BATTERY_ICON_COLOR="#2AA198"

# Volume segment
VOLUME_ICON_MIN=""
VOLUME_ICON_LOW=""
VOLUME_ICON_MEDIUM=""
VOLUME_ICON_HIGH=""
VOLUME_ICON_MAX=""
VOLUME_ICON_COLOR="#2AA198"

# Backlight segment
BACKLIGHT_ICON_LOW=""
BACKLIGHT_ICON_MEDIUM=""
BACKLIGHT_ICON_HIGH=""
BACKLIGHT_ICON_MAX=""
BACKLIGHT_ICON_COLOR="#2AA198"

# Processor usage segment
PROCESSOR_USAGE_ICON=""
PROCESSOR_USAGE_ICON_COLOR="#2AA198"

# Memory usage segment
MEMORY_USAGE_ICON=""
MEMORY_USAGE_ICON_COLOR="#2AA198"

# Disk usage segment
DISK_USAGE_ICON=""
DISK_USAGE_ICON_COLOR="#2AA198"

# Weather segment
WEATHER_ICON_HOT_DAY=""
WEATHER_ICON_COLD_DAY=""
WEATHER_ICON_HOT_NIGHT=""
WEATHER_ICON_COLD_NIGHT=""
WEATHER_ICON_CLOUDY=""
WEATHER_ICON_STORM=""
WEATHER_ICON_RAIN=""
WEATHER_ICON_SNOW=""
WEATHER_ICON_FOGGY=""
WEATHER_ICON_WINDY=""
WEATHER_ICON_COLOR="#2AA198"
WEATHER_LOCATION="742676"
WEATHER_UNIT="c"
WEATHER_URL="http://weather.yahooapis.com/forecastrss?w=$WEATHER_LOCATION&u=$WEATHER_UNIT"
WEATHER_DATA_SEPARATOR="|"

# Network segment
NETWORK_ICON_NONE=""
NETWORK_ICON_WIRELESS_VERY_LOW=""
NETWORK_ICON_WIRELESS_LOW=""
NETWORK_ICON_WIRELESS_MEDIUM=""
NETWORK_ICON_WIRELESS_HIGH=""
NETWORK_ICON_WIRELESS_VERY_HIGH=""
NETWORK_ICON_WIRED=""
NETWORK_ICON_COLOR="#2AA198"
NETWORK_INTERFACE_WIRED="eth0"
NETWORK_INTERFACE_WIRELESS="wlan0"

# Bandwidth segment
BANDWIDTH_ICON_DOWNLOAD=""
BANDWIDTH_ICON_UPLOAD=""
BANDWIDTH_ICON_DOWNLOAD_COLOR="#2AA198"
BANDWIDTH_ICON_UPLOAD_COLOR="#2AA198"

# Now playing segment
NOW_PLAYING_ICON=""
NOW_PLAYING_ICON_COLOR="#2AA198"
NOW_PLAYING_MAX_LEN="100"
NOW_PLAYING_METHOD="roll"
NOW_PLAYING_ROLL_SPEED="2"
NOW_PLAYING_MPD_HOST="localhost"
NOW_PLAYING_MPD_PORT="6600"
NOW_PLAYING_MPC_FORMAT="%artist% - %title%"
